apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: azure-web-search
        image: truthaniket/azure-web-search:latest
        ports:
        - containerPort: 6000

---

apiVersion: v1
kind: Service
metadata:
  name: service-html
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 6000
  selector:
    app: devops
